-- Seed: FBC 8th Edition (2023) canonical code sections.
-- First, ensure unique constraint exists so ON CONFLICT works.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fbc_code_sections_code_section_edition_key'
  ) THEN
    ALTER TABLE public.fbc_code_sections
      ADD CONSTRAINT fbc_code_sections_code_section_edition_key
      UNIQUE (code, section, edition);
  END IF;
END $$;

INSERT INTO public.fbc_code_sections
  (code, section, edition, title, requirement_text, keywords)
VALUES
('FBC', '302.1', '8th', 'Occupancy Classification',
 'Structures shall be classified with respect to occupancy in one or more of the groups listed in this section.',
 ARRAY['occupancy','classification','group','use']),
('FBC', '303.1', '8th', 'Assembly Group A',
 'Assembly Group A occupancy includes the use of a building or structure, or a portion thereof, for the gathering of persons for purposes such as civic, social or religious functions, recreation, food or drink consumption or awaiting transportation.',
 ARRAY['assembly','occupancy','group','A','gathering']),
('FBC', '304.1', '8th', 'Business Group B',
 'Business Group B occupancy includes the use of a building or structure, or a portion thereof, for office, professional or service-type transactions.',
 ARRAY['business','occupancy','group','B','office']),
('FBC', '306.1', '8th', 'Factory Group F',
 'Factory Group F occupancy includes the use of a building or structure, or a portion thereof, for assembling, disassembling, fabricating, finishing, manufacturing, packaging, repair or processing operations.',
 ARRAY['factory','occupancy','group','F','manufacturing']),
('FBC', '309.1', '8th', 'Mercantile Group M',
 'Mercantile Group M occupancy includes buildings and structures or portions thereof for the display and sale of merchandise, and involves stocks of goods, wares or merchandise incidental to such purposes.',
 ARRAY['mercantile','occupancy','group','M','retail','store']),
('FBC', '310.1', '8th', 'Residential Group R',
 'Residential Group R includes, among others, the use of a building or structure, or a portion thereof, for sleeping purposes when not classified as an Institutional Group I.',
 ARRAY['residential','occupancy','group','R','dwelling','sleeping']),
('FBC', '503.1', '8th', 'General Height and Area Limitations',
 'The building height, number of stories above grade plane and building area shall not exceed the limits specified in Table 504.3, Table 504.4 and Table 506.2.',
 ARRAY['height','area','stories','table','limitation']),
('FBC', '506.2', '8th', 'Allowable Area Increases - Sprinkler System Increase',
 'Where a building is equipped throughout with an automatic sprinkler system installed in accordance with Section 903.3.1.1, the value specified in Table 506.2 for maximum area per story is permitted to be multiplied by 3 in Group A, B, E, F-1, H-3, H-4, I-1, L, M, R, S-1 or U occupancies.',
 ARRAY['allowable','area','increase','sprinkler','automatic']),
('FBC', '602.2', '8th', 'Type I Construction',
 'Type I construction is that type of construction in which the building elements are of noncombustible materials and the fire-resistance ratings required by Table 601 are provided.',
 ARRAY['construction','type','I','noncombustible','fire-resistance']),
('FBC', '602.3', '8th', 'Type II Construction',
 'Type II construction is that type of construction in which the building elements are of noncombustible or limited combustible materials and the fire-resistance ratings required by Table 601 are provided.',
 ARRAY['construction','type','II','noncombustible','limited','combustible']),
('FBC', '602.4', '8th', 'Type III Construction',
 'Type III construction is that type of construction in which the exterior walls are of noncombustible materials and the interior building elements are of any material permitted by this code.',
 ARRAY['construction','type','III','exterior','noncombustible','interior']),
('FBC', '602.5', '8th', 'Type IV Construction - Heavy Timber',
 'Type IV construction is that type of construction in which the exterior walls are of noncombustible materials and the interior building elements are of solid or laminated wood without concealed spaces.',
 ARRAY['construction','type','IV','heavy','timber','wood']),
('FBC', '602.6', '8th', 'Type V Construction',
 'Type V construction is that type of construction in which the structural elements, exterior walls and interior walls are of any materials permitted by this code.',
 ARRAY['construction','type','V','wood','frame']),
('FBC', '703.1', '8th', 'Fire-Resistance Ratings - General',
 'Fire-resistance ratings shall be as specified in Table 601 for the type of construction and as specified in Table 602 for exterior walls.',
 ARRAY['fire-resistance','rating','construction','type','exterior','wall']),
('FBC', '706.1', '8th', 'Fire Walls',
 'Fire walls shall be constructed in accordance with Sections 706.1 through 706.12.',
 ARRAY['fire','wall','separation','rating','lot']),
('FBC', '707.1', '8th', 'Fire Barriers',
 'Fire barriers shall be constructed in accordance with Sections 707.1 through 707.14 and shall comply with Section 703.',
 ARRAY['fire','barrier','rating','wall','separation']),
('FBC', '708.1', '8th', 'Fire Partitions',
 'Fire partitions used to separate dwelling units in the same building shall have a fire-resistance rating of not less than 1 hour.',
 ARRAY['fire','partition','dwelling','unit','1-hour','separation']),
('FBC', '710.1', '8th', 'Horizontal Assemblies',
 'Horizontal assemblies required to have a fire-resistance rating by other provisions of this code including floor assemblies separating occupancies shall comply with this section.',
 ARRAY['horizontal','assembly','floor','fire-resistance','occupancy','separation']),
('FBC', '903.1', '8th', 'Automatic Sprinkler Systems - General',
 'Automatic sprinkler systems shall comply with this section.',
 ARRAY['automatic','sprinkler','system','fire','protection']),
('FBC', '903.2', '8th', 'Where Required',
 'Approved automatic sprinkler systems in new buildings and structures shall be provided in the locations described in Sections 903.2.1 through 903.2.12.',
 ARRAY['sprinkler','required','location','occupancy']),
('FBC', '903.3.1.1', '8th', 'NFPA 13 Sprinkler Systems',
 'Where the provisions of this code require that a building or portion thereof be equipped throughout with an automatic sprinkler system in accordance with this section, sprinklers shall be installed throughout in accordance with NFPA 13.',
 ARRAY['NFPA','13','sprinkler','system','automatic','throughout']),
('FBC', '905.1', '8th', 'Standpipe Systems',
 'Standpipe systems shall be provided in new buildings and structures in accordance with this section.',
 ARRAY['standpipe','system','hose','fire','department']),
('FBC', '907.1', '8th', 'Fire Alarm and Detection Systems - General',
 'Fire alarm systems and automatic fire detectors shall be provided in accordance with Sections 907.2 through 907.9.',
 ARRAY['fire','alarm','detection','system','automatic']),
('FBC', '907.2', '8th', 'Where Required - New Buildings',
 'An approved fire alarm system installed in accordance with the provisions of this code and NFPA 72 shall be provided in new buildings and structures.',
 ARRAY['fire','alarm','required','new','building','NFPA','72','notification']),
('FBC', '1004.1', '8th', 'Occupant Load - Design Occupant Load',
 'The number of occupants shall be computed at the rate of one occupant per unit of area as prescribed in Table 1004.5.',
 ARRAY['occupant','load','calculation','area','factor','table']),
('FBC', '1004.5', '8th', 'Occupant Load Table',
 'The occupant load factor for each function of space shall be in accordance with Table 1004.5.',
 ARRAY['occupant','load','factor','table','function','space']),
('FBC', '1005.1', '8th', 'Minimum Required Egress Width',
 'The minimum width or required capacity of components of the means of egress system shall be determined in accordance with this section.',
 ARRAY['egress','width','capacity','minimum','means','component']),
('FBC', '1006.1', '8th', 'Exits - Number of Exits and Exit Access Doorways',
 'The number of exits or access to exits shall be in compliance with the provisions of this section.',
 ARRAY['exit','number','required','access','doorway']),
('FBC', '1006.2', '8th', 'Egress from Stories or Occupied Roofs',
 'The means of egress for stories and occupied roofs shall comply with the applicable requirements of Sections 1006.2.1 through 1006.2.3 for the number of exits provided.',
 ARRAY['exit','story','occupied','roof','egress']),
('FBC', '1006.2.1', '8th', 'Single Exit - Conditions',
 'Only one exit or access to one exit is required from a story or occupied roof where one of the conditions described in Sections 1006.2.1.1 through 1006.2.1.4 is met.',
 ARRAY['single','exit','one','story','condition','common','path']),
('FBC', '1006.3', '8th', 'Egress from Spaces - Minimum Number of Exits',
 'The number of exits or exit access doorways required from any space shall be determined in accordance with this section.',
 ARRAY['exits','required','space','minimum','number','doorway']),
('FBC', '1017.1', '8th', 'Exit Access Travel Distance',
 'Travel distance within the exit access portion of the means of egress shall not exceed that specified in Table 1017.1.',
 ARRAY['travel','distance','exit','access','table','maximum']),
('FBC', '1017.2', '8th', 'Common Path of Egress Travel',
 'The common path of egress travel shall not exceed the distances given in Table 1017.2.',
 ARRAY['common','path','egress','travel','distance','table']),
('FBC', '1020.1', '8th', 'Corridors - General',
 'Corridors shall be fire-resistance rated in accordance with Table 1020.1.',
 ARRAY['corridor','fire-resistance','rated','wall','partition']),
('FBC', '1020.2', '8th', 'Corridor Width and Capacity',
 'The minimum corridor width shall be as determined in Section 1005.1, but not less than 44 inches. Corridors serving an occupant load of less than 50 shall have a minimum width of 36 inches.',
 ARRAY['corridor','width','44','36','inches','minimum','capacity']),
('FBC', '1023.1', '8th', 'Interior Exit Stairways and Ramps - General',
 'Interior exit stairways and ramps shall comply with Sections 1023.1 through 1023.12.',
 ARRAY['interior','exit','stairway','ramp','enclosure']),
('FBC', '1023.2', '8th', 'Construction - Stairway Enclosure',
 'Interior exit stairways shall be enclosed with fire barriers constructed in accordance with Section 707 or horizontal assemblies. The fire-resistance rating shall be not less than 2 hours where connecting four stories or more.',
 ARRAY['stairway','enclosure','fire-resistance','2-hour','barrier','four','stories']),
('FBC', '1027.1', '8th', 'Exit Discharge',
 'Exits shall discharge directly to the exterior of the building. The exit discharge shall be at grade or shall provide direct access to grade.',
 ARRAY['exit','discharge','exterior','grade','direct']),
('FBC', '1008.1', '8th', 'Means of Egress Illumination - General',
 'The means of egress, including the exit discharge, shall be illuminated at all times the building space served by the means of egress is occupied.',
 ARRAY['illumination','egress','lighting','exit','occupied']),
('FBC', '1013.1', '8th', 'Exit Signs - General',
 'Exits and exit access doorways from a room or area of a building shall be marked by approved exit signs readily visible from any direction of egress travel.',
 ARRAY['exit','sign','required','visible','marking','illuminated']),
('FBC', '1101.1', '8th', 'Accessibility - Scope',
 'The provisions of this chapter and Florida Accessibility Code shall control the design and construction of facilities for accessibility to physically disabled persons.',
 ARRAY['accessibility','disabled','Florida','code','scope']),
('FBC', '1104.1', '8th', 'Accessible Routes - General',
 'Accessible routes shall be provided in accordance with Sections 1104.1 through 1104.4 and shall comply with Chapter 4 of ICC A117.1.',
 ARRAY['accessible','route','general','required']),
('FBC', '1603.1', '8th', 'General Construction Documents',
 'Construction documents shall show the size, section and relative locations of structural members with floor levels, column centers and offsets dimensioned.',
 ARRAY['structural','construction','documents','design','loads','member']),
('FBC', '1604.1', '8th', 'General Structural Strength',
 'Buildings and other structures, and all parts thereof, shall be designed and constructed to support safely the loads prescribed herein.',
 ARRAY['structural','strength','design','loads','allowable','stress']),
('FBC', '1609.1', '8th', 'Wind Loads - Applicability',
 'Buildings and other structures shall be designed and constructed to resist wind loads as specified in this section.',
 ARRAY['wind','load','design','ASCE','7','resist','structure']),
('FBC', '1609.3', '8th', 'Basic Wind Speed',
 'The basic wind speed, V, used in the determination of design wind loads for buildings and other structures shall be determined from Figure 1609.3(1) through Figure 1609.3(8) based on the risk category of the building or structure.',
 ARRAY['wind','speed','basic','Vult','figure','risk','category']),
('FBC', '1612.1', '8th', 'Flood Loads - General',
 'Within flood hazard areas as established in Section 1612.3, all new construction of buildings, structures and portions of buildings and structures shall be designed and constructed to resist the effects of flood hazards and flood loads.',
 ARRAY['flood','load','hazard','area','design','construction']),
('FBC', '1704.1', '8th', 'Special Inspections - General',
 'Construction requiring special inspection shall include the materials, construction, fabrication and erection of all new buildings and structures and alterations to existing buildings and structures.',
 ARRAY['special','inspection','required','fabrication','erection']),
('FAC', '206.2.3', '8th', 'Elevator Required - Multi-Story Buildings',
 'At least one accessible route shall connect each story and mezzanine in multi-story buildings and facilities. In Florida, an elevator or other means of vertical access is required in buildings with three or more stories above or below grade, or any story with 3,000 or more square feet.',
 ARRAY['elevator','accessible','route','multi-story','Florida','3000','square','feet','stories']),
('FAC', '208.2', '8th', 'Accessible Parking - Number Required',
 'Parking spaces complying with 502 shall be provided in accordance with Table 208.2.',
 ARRAY['parking','accessible','spaces','table','required','count']),
('FAC', '404.2.4', '8th', 'Door Maneuvering Clearances',
 'Doors, doorways, and gates that are part of an accessible route shall comply with 404. Maneuvering clearances shall be provided at doors and doorways.',
 ARRAY['door','maneuvering','clearance','accessible','route','push','pull']),
('FAC', '604.3', '8th', 'Water Closet - Clearance',
 'A clearance around a water closet shall be provided measuring 60 inches minimum measured perpendicular from the side wall and 56 inches minimum measured perpendicular from the rear wall.',
 ARRAY['water','closet','clearance','60','56','inches','toilet','restroom']),
('FBC-EC', 'C402.1.3', '8th', 'Opaque Thermal Envelope Insulation - Minimum Requirements',
 'Opaque elements of the building thermal envelope shall comply with the insulation and assembly maximum U-factors in Table C402.1.3 and Table C402.1.4, or the R-values in Table C402.1.3.',
 ARRAY['insulation','R-value','thermal','envelope','roof','wall','table','minimum']),
('FBC-EC', 'C402.4', '8th', 'Air Leakage - Thermal Envelope',
 'The thermal envelope of buildings shall comply with Sections C402.4.1 through C402.4.4.',
 ARRAY['air','leakage','barrier','thermal','envelope','continuous']),
('FBC-EC', 'C403.1', '8th', 'Mechanical Systems - General',
 'Mechanical systems and equipment used to provide heating, cooling, and ventilation in buildings shall comply with the provisions of this section.',
 ARRAY['mechanical','heating','cooling','ventilation','HVAC','efficiency']),
('FBC-EC', 'C403.3', '8th', 'Simple HVAC Systems and Equipment',
 'Equipment shall have a minimum efficiency as specified in Tables C403.3.2(1) through C403.3.2(7) using the applicable rating conditions and minimum efficiency requirements.',
 ARRAY['HVAC','equipment','efficiency','minimum','SEER','EER','IEER','table']),
('FBC-EC', 'C405.2', '8th', 'Interior Lighting Controls',
 'Lighting systems shall be provided with controls as required by Sections C405.2.1 through C405.2.4.',
 ARRAY['lighting','controls','occupancy','sensor','daylight','interior']),
('FBC-EC', 'C405.3', '8th', 'Exterior Lighting Controls',
 'Exterior lighting for parking lots, garages, sales and non-sales canopies and overhangs, and the building facade shall comply with Section C405.3.',
 ARRAY['exterior','lighting','controls','parking','facade']),
('FBC-M', '403.1', '8th', 'Ventilation - General',
 'Mechanical ventilation systems shall be provided in accordance with this chapter and Section C403 of the Florida Building Code, Energy Conservation.',
 ARRAY['ventilation','mechanical','outdoor','air','required']),
('FBC-M', '403.3.1.1', '8th', 'Ventilation Rate Procedure',
 'The outdoor airflow rate, Vot, for the ventilation rate procedure shall be determined in accordance with Equation 4-1 and the requirements of Sections 403.3.1.1 through 403.3.1.1.4.',
 ARRAY['outdoor','air','ventilation','rate','cfm','occupancy','procedure']),
('FBC-P', '403.1', '8th', 'Minimum Plumbing Facilities',
 'The minimum number of plumbing fixtures, as determined by Section 403.2, required for the type of occupancy and use and the number of occupants shall be in accordance with Table 403.1.',
 ARRAY['plumbing','fixture','minimum','table','occupancy','count','required']),
('FBC', '1705.1', '8th', 'Required Verification and Inspection',
 'Special inspections and tests, where required by this chapter, shall be performed by an approved agency and shall comply with the applicable referenced standards.',
 ARRAY['special','inspection','test','approved','agency','standard']),
('FBC', '1620.1', '8th', 'High Velocity Hurricane Zone - General',
 'Buildings and structures to be built or relocated in the HVHZ shall be designed and constructed to comply with the requirements of Sections 1620 through 1626.',
 ARRAY['HVHZ','high','velocity','hurricane','zone','design','construction']),
('FBC', '1620.2', '8th', 'HVHZ Basic Wind Speed',
 'The basic wind speed for the HVHZ shall not be less than 175 mph (ultimate design wind speed, Vult). The design wind pressures used shall be based on this speed.',
 ARRAY['HVHZ','wind','speed','175','mph','ultimate','Vult','design','pressure']),
('FBC', '1623.1', '8th', 'Exterior Wall Coverings - HVHZ',
 'All exterior wall covering products and systems installed in the HVHZ shall be tested and approved per Miami-Dade County protocol, or shall bear an approval bearing an FL number issued by the Florida Building Commission for the specific product and application in HVHZ.',
 ARRAY['exterior','wall','covering','HVHZ','NOA','FL','number','product','approval']),
('FBC', '1714.1', '8th', 'Window and Door Assemblies - Product Approval',
 'Window and door assemblies shall be installed in accordance with the manufacturer''s installation instructions and the product approval issued by the Florida Building Commission.',
 ARRAY['window','door','product','approval','FL','number','installation','manufacturer']),
('FBC', '903.2.1', '8th', 'Group A - Sprinkler Requirement',
 'An automatic sprinkler system shall be provided throughout buildings and portions thereof used as Group A occupancy where the fire area exceeds 12,000 square feet.',
 ARRAY['sprinkler','Group','A','assembly','fire','area','12000','square','feet']),
('FBC', '903.2.9', '8th', 'Group S-1 - Sprinkler Requirement',
 'An automatic sprinkler system shall be provided throughout all buildings containing a Group S-1 occupancy where the area of the Group S-1 exceeds 12,000 square feet.',
 ARRAY['sprinkler','storage','S-1','fire','area','12000']),
('FBC', '1609.4', '8th', 'Exposure Category',
 'For each wind direction considered, an exposure category that adequately reflects the characteristics of ground surface irregularities shall be determined for the site at which the building or structure is to be constructed.',
 ARRAY['exposure','category','B','C','D','wind','surface','roughness']),
('FBC', '1609.5', '8th', 'Risk Category',
 'Each building and structure shall be assigned a risk category in accordance with Table 1604.5.',
 ARRAY['risk','category','I','II','III','IV','building','table']),
('FBC', '508.4', '8th', 'Separated Occupancies',
 'Each portion of a building shall be individually classified in accordance with Section 302.1. The required separation between the occupancies shall be determined by Table 508.4.',
 ARRAY['separated','occupancy','separation','table','fire-resistance','rating']),
('FBC', '509.1', '8th', 'Incidental Uses',
 'Incidental use areas shall be separated or protected, or both, in accordance with Table 509.',
 ARRAY['incidental','use','separation','protection','table','boiler','storage']),
('FBC', '403.1', '8th', 'High-Rise Buildings - General',
 'The provisions of Sections 403.1 through 403.6 shall apply to buildings with an occupied floor located more than 75 feet above the lowest level of fire department vehicle access.',
 ARRAY['high-rise','75','feet','occupied','floor','fire','department','access']),
('FBC', '407.1', '8th', 'Group I-2 - Smoke Compartments',
 'Smoke barriers shall be provided to form a smoke compartment for every story used for sleeping or care of patients. The maximum floor area of a smoke compartment shall not exceed 22,500 square feet.',
 ARRAY['smoke','compartment','I-2','barrier','healthcare','22500','floor','area'])
ON CONFLICT (code, section, edition) DO NOTHING;